<p class="dist-eyebrow">FIRST, YOUR ACCOUNT</p><h2>A new market.<br><em>A familiar ambition.</em></h2><p>Create your distribution account to start your application. Already with Seller Africa? <a href="<?= e(app_url('login?as=distributor')) ?>">Sign in</a>.</p>
<?php if ($errors): ?><div class="errors" role="alert"><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form method="post" action="<?= e(app_url('distributor/register')) ?>" id="distribution-account-form">
<input type="hidden" name="csrf_token" value="<?= e(getCsrfToken()) ?>"><input type="hidden" name="started_at" value="<?= time() ?>"><input type="hidden" name="account_type" value="customer">
<div class="dist-honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div>
<div class="distribution-fields">
<?php foreach (['first_name'=>['First name','text','given-name'],'last_name'=>['Surname','text','family-name'],'email'=>['Email address','email','email'],'phone'=>['Phone, with country code','tel','tel']] as $key=>[$label,$type,$autocomplete]): ?><div class="field"><label for="account-<?= e($key) ?>"><?= e($label) ?> *</label><input id="account-<?= e($key) ?>" name="<?= e($key) ?>" type="<?= e($type) ?>" autocomplete="<?= e($autocomplete) ?>" required value="<?= e(is_scalar($_POST[$key] ?? '')?($_POST[$key] ?? ''):'') ?>" <?= $type==='tel'?'placeholder="+1 202 555 0123"':'' ?>></div><?php endforeach; ?>
<?php foreach (['password'=>'Password','password_confirmation'=>'Confirm password'] as $key=>$label): ?><div class="field"><label for="account-<?= $key ?>"><?= $label ?> *</label><div class="dist-password"><input id="account-<?= $key ?>" name="<?= $key ?>" type="password" minlength="5" required autocomplete="new-password"><button type="button" data-reveal="account-<?= $key ?>" aria-label="Show <?= strtolower($label) ?>">Show</button></div><?php if ($key==='password'): ?><small>Use at least 5 characters.</small><?php endif; ?></div><?php endforeach; ?>
<?php if (!empty($captchaRequired) && !empty($captchaChallenge)): ?><div class="field wide"><label for="account-captcha">Security check: <?= e($captchaChallenge['question']) ?></label><input id="account-captcha" name="captcha_answer" required inputmode="numeric"></div><?php endif; ?>
<label class="dist-consent wide"><input name="terms_consent" type="checkbox" value="1" required <?= !empty($_POST['terms_consent'])?'checked':'' ?>><span>I agree to the <a href="<?= e(app_url('terms')) ?>" target="_blank" rel="noopener">Terms</a> and <a href="<?= e(app_url('privacy-policy')) ?>" target="_blank" rel="noopener">Privacy Policy</a>.</span></label>
</div><div class="distribution-actions"><button type="submit">Create account &amp; continue <span aria-hidden="true">&#8594;</span></button></div><small class="dist-security">Your application is saved to your account. No payment is required to apply.</small></form>
