<link rel="stylesheet" href="<?= e(asset('css/distributor.css?v=2')) ?>">
<div class="dist-site">
<?php require __DIR__.'/header.php'; ?>
<main>
<section class="dist-hero"><img class="dist-hero-image" src="<?= e(asset('images/distributors-header.jpeg')) ?>" alt="Supermarket aisle lined with stocked grocery shelves" fetchpriority="high"><div class="dist-container dist-hero-content"><p class="dist-eyebrow">THE DISTRIBUTION PROGRAM</p><h1>African food.<br><em>Global shelves.</em></h1><p class="dist-hero-lead">Your next chapter starts in retail.</p><p>Connect your food brand with grocery, wholesale and foodservice opportunities in the U.S. and beyond.</p><div class="dist-actions"><a class="dist-button" href="<?= e(app_url('distributor/register')) ?>">Apply for shelf placement <span aria-hidden="true">&#8599;</span></a><a class="dist-text-link" href="<?= e(app_url('contact')) ?>">Speak with our team <span aria-hidden="true">&#8594;</span></a></div><div class="dist-hero-foot">Retail access <span aria-hidden="true">/</span> Readiness support <span aria-hidden="true">/</span> Long-term growth</div></div></section>
<section class="dist-section"><div class="dist-container dist-opportunities"><div><p class="dist-eyebrow">BEYOND THE MARKETPLACE</p><h2>Good products deserve<br><em>a wider audience.</em></h2><p>We work with African food brands to assess retail readiness and explore the right distribution channels.</p></div><div class="dist-channel-grid"><?php foreach (['Grocery retail'=>'Independent grocers, specialty stores and retail opportunities.','Wholesale'=>'Build relationships beyond one order at a time.','Foodservice'=>'Explore supply opportunities for restaurants and hospitality.','New markets'=>'Prepare your brand for its next market.'] as $name=>$description): ?><div><h3><?= e($name) ?></h3><p><?= e($description) ?></p></div><?php endforeach; ?></div></div></section>
<section class="dist-section dist-process"><div class="dist-container"><div class="dist-section-head"><div><p class="dist-eyebrow">HOW IT WORKS</p><h2>From your business<br><em>to the next shelf.</em></h2></div><p>A considered process. Practical support.<br>A clear next step for your brand.</p></div><ol class="dist-process-list"><?php $n=0; foreach (['Apply'=>'Tell us about your business, products and production capacity.','Review'=>'Our team assesses product fit, documentation and readiness.','Prepare'=>'Identify any compliance, packaging or market-entry needs.','Connect'=>'Approved brands explore suitable distribution opportunities.','Grow'=>'Build supply relationships and prepare to scale.'] as $name=>$description): ?><li><span><?= str_pad((string)++$n,2,'0',STR_PAD_LEFT) ?></span><h3><?= e($name) ?></h3><p><?= e($description) ?></p></li><?php endforeach; ?></ol></div></section>
<section class="dist-section"><div class="dist-container dist-requirements"><div><p class="dist-eyebrow">IS YOUR BRAND A GOOD FIT?</p><h2>Built for brands<br><em>ready to move forward.</em></h2><p>Start with what you have. Missing compliance documents do not automatically disqualify your application.</p></div><ul><?php foreach (['A legally registered business','Consistent product quality and supply capacity','Clear packaging, ingredient and allergen information','Documented shelf life and appropriate handling','Willingness to meet applicable market requirements','Openness to wholesale pricing and distributor margins'] as $item): ?><li><span aria-hidden="true">&#10003;</span><?= e($item) ?></li><?php endforeach; ?></ul></div></section>
<section class="dist-section dist-process" aria-labelledby="dist-retail-ready-title">
  <div class="dist-container dist-opportunities">
    <div><h2 id="dist-retail-ready-title">Your produce deserves a place on the <em>big shelves.</em></h2></div>
    <div>
      <p>Register with us and take the first step toward getting your products into mainstream supermarkets across the U.S. and U.K.</p>
      <p>We’re connecting export-ready African producers and brands to bigger markets, stronger distribution, and new retail opportunities.</p>
      <p><strong>From Africa to mainstream shelves.</strong></p>
      <a class="dist-button" href="<?= e(app_url('distributor/register')) ?>">Register today and get retail-ready.</a>
    </div>
  </div>
</section>
<?php require __DIR__.'/sellers.php'; ?>
<section class="dist-cta"><div class="dist-container"><p class="dist-eyebrow">YOUR NEXT CHAPTER</p><h2>Let’s find your<br><em>place on the shelf.</em></h2><a class="dist-button light" href="<?= e(app_url('distributor/register')) ?>">Start your application <span aria-hidden="true">&#8599;</span></a><p><a class="dist-text-link" href="<?= e(app_url('vendor/register')) ?>">Become a vendor <span aria-hidden="true">&#8594;</span></a></p><p>Applications are reviewed individually. Retail placement is not guaranteed.</p></div></section>
<section class="dist-section"><div class="dist-container dist-faq"><div><p class="dist-eyebrow">A FEW THINGS TO KNOW</p><h2>Good questions.<br><em>Clear answers.</em></h2></div><div><?php foreach (['Do I need to be export-ready to apply?'=>'No. Tell us your current readiness, including anything not available yet. Our team may recommend readiness support.','Can I still sell on the marketplace?'=>'Yes. Distribution applications are reviewed separately from marketplace selling.','What do I need for the application?'=>'Your registered business and contact details, product portfolio, production capacity, compliance information and retail goals.','What happens after I apply?'=>'Our team reviews your application and emails an outcome: Distribution Ready, Readiness Support Required, or Not Yet Ready.'] as $q=>$a): ?><details><summary><?= e($q) ?></summary><p><?= e($a) ?></p></details><?php endforeach; ?></div></div></section>
</main><footer class="dist-footer dist-container"><span>Seller Africa · African and Caribbean Marketplace</span><nav><a href="<?= e(app_url('privacy-policy')) ?>">Privacy</a><a href="<?= e(app_url('terms')) ?>">Terms</a><a href="<?= e(app_url('contact')) ?>">Contact</a></nav></footer></div>
