<style>.payment-link-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;max-width:850px}.payment-link-form label{display:grid;gap:8px}.payment-link-form input,.payment-link-form select{width:100%;min-width:0;min-height:48px}.payment-links-table{overflow-x:auto}.payment-link-url{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}.payment-link-url input{flex:1;min-width:0;min-height:48px}.payment-link-form button{justify-self:start}@media(max-width:640px){.payment-link-form{grid-template-columns:1fr}.payment-link-url input{flex-basis:100%}}</style>
<section class="panel"><div class="panel-header"><div><h2>Payment Links</h2><p>Customer services and subscriptions</p></div></div>
<?php if($error): ?><p role="alert"><?= e($error) ?></p><?php endif; ?>
<?php if($notice): ?><p role="status"><?= e($notice) ?></p><?php endif; ?>
<form method="post" class="payment-link-form"><input type="hidden" name="csrf_token" value="<?= e(getCsrfToken()) ?>"><input type="hidden" name="action" value="generate">
<label>Customer name<input required name="name" maxlength="190" autocomplete="name" value="<?= e($_POST['name'] ?? $customer['display_name'] ?? '') ?>"></label>
<label>Account email<input required type="email" name="email" maxlength="190" autocomplete="email" value="<?= e($_POST['email'] ?? $customer['email'] ?? '') ?>"></label>
<label>Service<select name="service" id="link-service" required><?php foreach($catalog as $key=>$item): ?><option value="<?= e($key) ?>" data-providers="<?= e(implode(',',$item['providers'])) ?>" <?= ($_POST['service'] ?? '')===$key?'selected':'' ?>><?= e($item['label']) ?></option><?php endforeach; ?></select></label>
<label>Payment method<select name="provider" id="link-provider" required><option value="paystack" <?= ($_POST['provider'] ?? '')==='paystack'?'selected':'' ?>>Paystack</option><option value="stripe" <?= ($_POST['provider'] ?? '')==='stripe'?'selected':'' ?>>Stripe</option></select></label>
<button class="btn primary" type="submit">Generate payment link</button></form>
<p>Links are assigned to the email above. Vendor and distributor services require an existing account. Creating a link does not activate a service. Checkout links can expire; generate a fresh link when needed. Priority: Stripe renews automatically; Paystack charges in naira for one period with manual renewal.</p>
<?php if($selected): ?><h3><?= e($selected['label']) ?></h3><p><?= e($selected['customer_email']) ?></p><div class="payment-link-url"><input id="generated-link" readonly aria-label="Generated checkout link" value="<?= e($selected['checkout_url']) ?>"><button class="btn secondary" type="button" id="copy-payment-link">Copy link</button><a class="btn secondary" target="_blank" rel="noopener noreferrer" href="<?= e($selected['checkout_url']) ?>">Open checkout</a></div><span id="copy-status" role="status"></span>
<form method="post"><input type="hidden" name="csrf_token" value="<?= e(getCsrfToken()) ?>"><input type="hidden" name="action" value="email"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><button class="btn primary">Email payment link</button></form><?php endif; ?>
</section><section class="panel"><h3>Recently generated</h3><div class="payment-links-table"><table class="data-table"><thead><tr><th>Customer</th><th>Service</th><th>Provider</th><th>Created</th><th>Link</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= e($row['customer_name']) ?><br><?= e($row['customer_email']) ?></td><td><?= e($row['label']) ?></td><td><?= e(ucfirst($row['provider'])) ?></td><td><?= e($row['created_at']) ?></td><td><a href="<?= e(app_url('dashboard/payment-links?link='.$row['id'])) ?>">View link</a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="5">No payment links generated yet.</td></tr><?php endif; ?></tbody></table></div></section>
<script>
const service=document.getElementById('link-service'),provider=document.getElementById('link-provider');
function updateProviders(){const allowed=service.selectedOptions[0].dataset.providers.split(',');for(const option of provider.options){option.disabled=!allowed.includes(option.value);option.hidden=option.disabled;}if(!allowed.includes(provider.value))provider.value=allowed[0];}
service.addEventListener('change',updateProviders);updateProviders();
document.getElementById('copy-payment-link')?.addEventListener('click',async()=>{const input=document.getElementById('generated-link');try{await navigator.clipboard.writeText(input.value);document.getElementById('copy-status').textContent='Link copied.';}catch(e){input.select();document.getElementById('copy-status').textContent='Select and copy the payment link above.';}});
document.querySelector('.payment-link-form').addEventListener('submit',function(){const b=this.querySelector('button');b.disabled=true;b.textContent='Generating...';});
window.addEventListener('pageshow',()=>{const b=document.querySelector('.payment-link-form button');b.disabled=false;b.textContent='Generate payment link';});
</script>
