<?php

$navigation = [
    'Dashboard' => [
        ['label' => 'Overview', 'href' => 'dashboard', 'key' => 'overview'],
        ['label' => 'Sales Analytics', 'href' => 'dashboard/sales-analytics', 'key' => 'sales-analytics'],
        ['label' => 'Revenue Report', 'href' => 'dashboard/revenue-report', 'key' => 'revenue-report'],
        ['label' => 'Vendor Performance', 'href' => 'dashboard/vendor-performance', 'key' => 'vendor-performance'],
        ['label' => 'Affiliate Performance', 'href' => 'dashboard/affiliate-performance', 'key' => 'affiliate-performance'],
    ],
    'Users' => [
        ['label' => 'Payment Links', 'href' => 'dashboard/payment-links', 'key' => 'payment-links'],
        ['label' => 'All Users', 'href' => 'dashboard/users', 'key' => 'users'],
        ['label' => 'Buyers', 'href' => 'dashboard/buyers', 'key' => 'buyers'],
        ['label' => 'Guest Buyers', 'href' => 'dashboard/guest-buyers', 'key' => 'guest-buyers'],
        ['label' => 'Blocked Users', 'href' => 'dashboard/blocked-users', 'key' => 'blocked-users'],
        ['label' => 'User Activity Logs', 'href' => 'dashboard/user-activity-logs', 'key' => 'user-activity-logs'],
    ],
    'Vendors' => [
        ['label' => 'Priority Members', 'href' => 'dashboard/priority-members', 'key' => 'priority-members'],
        ['label' => 'Set Up a Store', 'href' => 'dashboard/set-up-store', 'key' => 'set-up-store'],
        ['label' => 'Distribution Applications', 'href' => 'dashboard/distributors', 'key' => 'distributors'],
        ['label' => 'All Vendors', 'href' => 'dashboard/vendors', 'key' => 'vendors'],
        ['label' => 'Vendor Packages', 'href' => 'dashboard/vendor-packages', 'key' => 'vendor-packages'],
        ['label' => 'Vendor Subscriptions', 'href' => 'dashboard/vendor-subscriptions', 'key' => 'vendor-subscriptions'],
        ['label' => 'Pending Vendors', 'href' => 'dashboard/pending-vendors', 'key' => 'pending-vendors'],
        ['label' => 'Verified Vendors', 'href' => 'dashboard/verified-vendors', 'key' => 'verified-vendors'],
        ['label' => 'Rejected Vendors', 'href' => 'dashboard/rejected-vendors', 'key' => 'rejected-vendors'],
        ['label' => 'Vendor KYC Documents', 'href' => 'dashboard/vendor-kyc-documents', 'key' => 'vendor-kyc-documents'],
        ['label' => 'Vendor Stores', 'href' => 'dashboard/vendor-stores', 'key' => 'vendor-stores'],
        ['label' => 'Vendor Ratings', 'href' => 'dashboard/vendor-ratings', 'key' => 'vendor-ratings'],
        ['label' => 'Vendor Payout Accounts', 'href' => 'dashboard/vendor-payout-accounts', 'key' => 'vendor-payout-accounts'],
    ],
    'Products' => [
        ['label' => 'All Products', 'href' => 'dashboard/products', 'key' => 'products'],
        ['label' => 'Pending Approval', 'href' => 'dashboard/pending-products', 'key' => 'pending-products'],
        ['label' => 'Approved Products', 'href' => 'dashboard/approved-products', 'key' => 'approved-products'],
        ['label' => 'Rejected Products', 'href' => 'dashboard/rejected-products', 'key' => 'rejected-products'],
        ['label' => 'Featured Products', 'href' => 'dashboard/featured-products', 'key' => 'featured-products'],
        ['label' => 'Ranked Products', 'href' => 'dashboard/ranked-products', 'key' => 'ranked-products'],
        ['label' => 'Low Stock Products', 'href' => 'dashboard/low-stock-products', 'key' => 'low-stock-products'],
        ['label' => 'Out of Stock Products', 'href' => 'dashboard/out-of-stock-products', 'key' => 'out-of-stock-products'],
        ['label' => 'Product Comments', 'href' => 'dashboard/product-comments', 'key' => 'product-comments'],
        ['label' => 'Product Reviews', 'href' => 'dashboard/product-reviews', 'key' => 'product-reviews'],
        ['label' => 'Product Meta Tags', 'href' => 'dashboard/product-meta-tags', 'key' => 'product-meta-tags'],
    ],
    'Categories & Brands' => [
        ['label' => 'Categories', 'href' => 'dashboard/categories', 'key' => 'categories'],
        ['label' => 'Subcategories', 'href' => 'dashboard/subcategories', 'key' => 'subcategories'],
        ['label' => 'Brands', 'href' => 'dashboard/brands', 'key' => 'brands'],
        ['label' => 'Attributes', 'href' => 'dashboard/attributes', 'key' => 'attributes'],
        ['label' => 'Variations', 'href' => 'dashboard/variations', 'key' => 'variations'],
    ],
    'Orders' => [
        ['label' => 'All Orders', 'href' => 'dashboard/orders', 'key' => 'orders'],
        ['label' => 'Pending Orders', 'href' => 'dashboard/pending-orders', 'key' => 'pending-orders'],
        ['label' => 'Processing Orders', 'href' => 'dashboard/processing-orders', 'key' => 'processing-orders'],
        ['label' => 'Shipped Orders', 'href' => 'dashboard/shipped-orders', 'key' => 'shipped-orders'],
        ['label' => 'Delivered Orders', 'href' => 'dashboard/delivered-orders', 'key' => 'delivered-orders'],
        ['label' => 'Cancelled Orders', 'href' => 'dashboard/cancelled-orders', 'key' => 'cancelled-orders'],
        ['label' => 'Returned Orders', 'href' => 'dashboard/returned-orders', 'key' => 'returned-orders'],
    ],
    'Payments' => [
        ['label' => 'Transactions', 'href' => 'dashboard/transactions', 'key' => 'transactions'],
        ['label' => 'Payment Gateways', 'href' => 'dashboard/payment-gateways', 'key' => 'payment-gateways'],
        ['label' => 'Failed Payments', 'href' => 'dashboard/failed-payments', 'key' => 'failed-payments'],
        ['label' => 'Idempotency Logs', 'href' => 'dashboard/idempotency-logs', 'key' => 'idempotency-logs'],
        ['label' => 'Multi-Currency Settings', 'href' => 'dashboard/multi-currency-settings', 'key' => 'multi-currency-settings'],
    ],
    'Withdrawals' => [
        ['label' => 'Vendor Withdrawals', 'href' => 'dashboard/vendor-withdrawals', 'key' => 'vendor-withdrawals'],
        ['label' => 'Affiliate Withdrawals', 'href' => 'dashboard/affiliate-withdrawals', 'key' => 'affiliate-withdrawals'],
        ['label' => 'Pending Withdrawals', 'href' => 'dashboard/pending-withdrawals', 'key' => 'pending-withdrawals'],
        ['label' => 'Approved Withdrawals', 'href' => 'dashboard/approved-withdrawals', 'key' => 'approved-withdrawals'],
        ['label' => 'Rejected Withdrawals', 'href' => 'dashboard/rejected-withdrawals', 'key' => 'rejected-withdrawals'],
    ],
    'Shipping' => [
        ['label' => 'Shipping Zones', 'href' => 'dashboard/shipping-zones', 'key' => 'shipping-zones'],
        ['label' => 'Shipping Rates', 'href' => 'dashboard/shipping-rates', 'key' => 'shipping-rates'],
        ['label' => 'Aramex API Settings', 'href' => 'dashboard/aramex-api-settings', 'key' => 'aramex-api-settings'],
        ['label' => 'Shipment Tracking', 'href' => 'dashboard/shipment-tracking', 'key' => 'shipment-tracking'],
        ['label' => 'Delivery Partners', 'href' => 'dashboard/delivery-partners', 'key' => 'delivery-partners'],
    ],
    'Affiliate System' => [
        ['label' => 'Affiliates', 'href' => 'dashboard/affiliates', 'key' => 'affiliates'],
        ['label' => 'Referral Links', 'href' => 'dashboard/referral-links', 'key' => 'referral-links'],
        ['label' => 'Commission Rules', 'href' => 'dashboard/commission-rules', 'key' => 'commission-rules'],
        ['label' => 'Pending Commissions', 'href' => 'dashboard/pending-commissions', 'key' => 'pending-commissions'],
        ['label' => 'Approved Commissions', 'href' => 'dashboard/approved-commissions', 'key' => 'approved-commissions'],
        ['label' => 'Affiliate Payouts', 'href' => 'dashboard/affiliate-payouts', 'key' => 'affiliate-payouts'],
    ],
    'Marketing' => [
        ['label' => 'Coupons', 'href' => 'dashboard/coupons', 'key' => 'coupons'],
        ['label' => 'Albums', 'href' => 'dashboard/albums', 'key' => 'albums'],
        ['label' => 'Gallery', 'href' => 'dashboard/gallery', 'key' => 'gallery'],
        ['label' => 'Blog & News', 'href' => 'dashboard/blog-posts', 'key' => 'blog-posts'],
        ['label' => 'Popups', 'href' => 'dashboard/popups', 'key' => 'popups'],
        ['label' => 'Sliders', 'href' => 'dashboard/sliders', 'key' => 'sliders'],
        ['label' => 'Ads Banners', 'href' => 'dashboard/ads-banners', 'key' => 'ads-banners'],
        ['label' => 'Announcements', 'href' => 'dashboard/announcements', 'key' => 'announcements'],
        ['label' => 'Email Campaigns', 'href' => 'dashboard/email-campaigns', 'key' => 'email-campaigns'],
        ['label' => 'Abandoned Cart Emails', 'href' => 'dashboard/abandoned-cart-emails', 'key' => 'abandoned-cart-emails'],
        ['label' => 'Pixels', 'href' => 'dashboard/marketing-pixels', 'key' => 'marketing-pixels'],
    ],
    'Refunds & Disputes' => [
        ['label' => 'Refund Requests', 'href' => 'dashboard/refund-requests', 'key' => 'refund-requests'],
        ['label' => 'Vendor Disputes', 'href' => 'dashboard/vendor-disputes', 'key' => 'vendor-disputes'],
        ['label' => 'Buyer Complaints', 'href' => 'dashboard/buyer-complaints', 'key' => 'buyer-complaints'],
        ['label' => 'Return Requests', 'href' => 'dashboard/return-requests', 'key' => 'return-requests'],
    ],
    'Notifications' => [
        ['label' => 'In-App Notifications', 'href' => 'dashboard/in-app-notifications', 'key' => 'in-app-notifications'],
        ['label' => 'Email Notifications', 'href' => 'dashboard/email-notifications', 'key' => 'email-notifications'],
        ['label' => 'SMS Notifications', 'href' => 'dashboard/sms-notifications', 'key' => 'sms-notifications'],
        ['label' => 'Push Notifications', 'href' => 'dashboard/push-notifications', 'key' => 'push-notifications'],
    ],
    'System Automation' => [
        ['label' => 'Data Migration', 'href' => 'dashboard/data-migration', 'key' => 'data-migration'],
        ['label' => 'Cron Jobs', 'href' => 'dashboard/cron-jobs', 'key' => 'cron-jobs'],
        ['label' => 'Queues', 'href' => 'dashboard/queues', 'key' => 'queues'],
        ['label' => 'Worker Monitor', 'href' => 'dashboard/worker-monitor', 'key' => 'worker-monitor'],
        ['label' => 'Failed Jobs', 'href' => 'dashboard/failed-jobs', 'key' => 'failed-jobs'],
        ['label' => 'Email Scheduler', 'href' => 'dashboard/email-scheduler', 'key' => 'email-scheduler'],
        ['label' => 'Cart Checker', 'href' => 'dashboard/cart-checker', 'key' => 'cart-checker'],
        ['label' => 'Cleanup Tasks', 'href' => 'dashboard/cleanup-tasks', 'key' => 'cleanup-tasks'],
    ],
    'Settings' => [
        ['label' => 'Admin Profile', 'href' => 'dashboard/admin-profile', 'key' => 'admin-profile'],
        ['label' => 'General Settings', 'href' => 'dashboard/general-settings', 'key' => 'general-settings'],
        ['label' => 'Store Settings', 'href' => 'dashboard/store-settings', 'key' => 'store-settings'],
        ['label' => 'Currency Settings', 'href' => 'dashboard/currency-settings', 'key' => 'currency-settings'],
        ['label' => 'Tax Settings', 'href' => 'dashboard/tax-settings', 'key' => 'tax-settings'],
        ['label' => 'SEO Settings', 'href' => 'dashboard/seo-settings', 'key' => 'seo-settings'],
        ['label' => 'Mail Settings', 'href' => 'dashboard/mail-settings', 'key' => 'mail-settings'],
        ['label' => 'Security Settings', 'href' => 'dashboard/security-settings', 'key' => 'security-settings'],
        ['label' => 'Role & Permissions', 'href' => 'dashboard/role-permissions', 'key' => 'role-permissions'],
        ['label' => 'Audit Logs', 'href' => 'dashboard/audit-logs', 'key' => 'audit-logs'],
        ['label' => 'Queue & Worker Monitor', 'href' => 'dashboard/queue-worker-monitor', 'key' => 'queue-worker-monitor'],
        ['label' => 'Audit Hub', 'href' => 'dashboard/audit-hub', 'key' => 'audit-hub'],
    ],
];

return \App\AdminAccessService::filterNavigation($navigation, $_SESSION['roles'] ?? []);
