AliasMatch "^/btcpay(?:/.*)?$" "/opt/btcpay-control/public/index.php"
<Directory "/opt/btcpay-control/public">
    Options -Indexes -ExecCGI
    AllowOverride None
    Require all granted
</Directory>
<LocationMatch "^/btcpay(?:/.*)?$">
    SetHandler "proxy:unix:/run/btcpay-control/php-fpm.sock|fcgi://localhost"
</LocationMatch>
